# Generated by Django 5.1.7 on 2025-04-29 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_veiculo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cor',
            old_name='name',
            new_name='nome',
        ),
    ]
